### ISSUE TITLE
it doesnt appear to merge when a character is removed?

### ISSUE THREAD

**Issue by ghost** [collaborative-ruby/ruby-writes-fizzbuzz#442]
this has been happening with the 3 open prs now, PLS FIX

**Comment by nilsding** [comment]
i think @0x0dea disabled the automerge-bot because of this: 
![420 merged PRs](https://cloud.githubusercontent.com/assets/1809170/11221788/3e42ac38-8d67-11e5-9de8-43903d32cb22.png)

**Comment by ghost** [comment]
thats pretty sick yo

**Comment by snowe2010** [comment]
pretty sure he disabled it because of tom-lord, who created a separate git account and began spamming pull requests so fast nobody could commit.

**Comment by nilsding** [comment]
oh well.  It was fun while it lasted.

**Comment by snowe2010** [comment]
ya

**Comment by ghost** [comment]
lets show some solidarity

**Comment by snowe2010** [comment]
o7
